version: '3'
services:
  nginx:
    build: server/nginx/
    ports:
      - "8080:80"
    networks:
      - nuwf
  uwsgi:
    build: server/uwsgi/
    ports:
      - "9090:9090"
    networks:
      - nuwf
      
networks:
  nuwf:
    driver: bridge
